// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6-G3e1g3xMjuxA6btD5ATWVfbnvSI2A',
    appId: '1:64165223895:web:cc53b483e4251388183f92',
    messagingSenderId: '64165223895',
    projectId: 'fir-flutter-codelab-880ad',
    authDomain: 'fir-flutter-codelab-880ad.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-880ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgDm_c7GLBTh5OegvjOUHpwUpForDbnw',
    appId: '1:64165223895:android:7af2592652061d7f183f92',
    messagingSenderId: '64165223895',
    projectId: 'fir-flutter-codelab-880ad',
    storageBucket: 'fir-flutter-codelab-880ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNngVHZfE4qJejUGY3R9Rp41kIKR-7DM',
    appId: '1:64165223895:ios:fd53bd4e0dcbcaa8183f92',
    messagingSenderId: '64165223895',
    projectId: 'fir-flutter-codelab-880ad',
    storageBucket: 'fir-flutter-codelab-880ad.appspot.com',
    iosClientId: '64165223895-i21850ko4imd9f44nvpq9v686t4gks1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnNngVHZfE4qJejUGY3R9Rp41kIKR-7DM',
    appId: '1:64165223895:ios:fd53bd4e0dcbcaa8183f92',
    messagingSenderId: '64165223895',
    projectId: 'fir-flutter-codelab-880ad',
    storageBucket: 'fir-flutter-codelab-880ad.appspot.com',
    iosClientId: '64165223895-i21850ko4imd9f44nvpq9v686t4gks1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
